name: Test & Deploy to Production
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: DigitalOcean
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ./test.sh


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: DigitalOcean
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ./deploy.sh
