name: Deployment to Production
on: [push]
jobs:
  build:
    name: Deployment Process
    runs-on: ubuntu-latest
    environment: DigitalOcean
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        run: echo ${{ secrets.KEY_ED25519 }} | base64 -d > test_KEY_ED25519
    - name: Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ./build.sh
    - name: Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ./test.sh
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ./deploy.sh
