name: Restart app
on:
  issues:
    types: [labeled]
  workflow_dispatch:
jobs:
  build:
    name: Restart app
    runs-on: ubuntu-latest
    environment: DigitalOcean
    steps:
    - name: Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ./restart.sh
